- name : Pre-installation tests
  ansible.builtin.import_tasks: "test.yaml"

- name : Watch variables
  debug: 
    msg: "SERVICE IS : {{ k3s_service }}"

- name: "K3s script execution"
  ansible.builtin.script: "{{ role_path }}/files/k3s-installation.sh"
  register: k3s_output_install
  when: k3s_service != "active"

- name: "Save K3s installation output to a log file"
  ansible.builtin.copy:
    content: "{{ k3s_output_install.stdout }}"
    dest: "{{ role_path }}/logs/k3s-installation.log"
    mode: '0644'
  when: k3s_output_install.changed | default(false)